---
title: "Notes"
author: "Sammi Johnson"
date: "2025-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Objective: KASP analysis

## Rlm7

- allele of the gene wall-assoc kinase-like (WAKL)
- resistance to blackleg disease
- resistance is race-specific
  - AvrLm7 resistant to neither
  - AvrLm4-7 resistant to rLm-4 and rLm-7
  
  
## KASP Marker

today we'll use a specific kasp marker to screen our 12 genos for our practical
(6 per day)

quencher is outcompeted when the allele we're testing for is present
- ergo, presence makes fluorescent


### PCR

Master mix:
- ddNTPs
- magnesium
- dnaases
- primers
- buffer

Kasp master mix + 9.2 µl KASP primers mixture, the latter containing:
- common primer
- allele specific primer for allele A
- allele specific primer for allele B
- distilled water


384 well PCR plate + template control (using distilled water instead of DNA)

## KASP Analysis

Do this during the PCR

check FAM signal fluoro vs HEX signal fluoro
- clusters into homozygous on X, homozyg on Y, hetero in between them
- or cluster at origin for control or absence of either allele


## SNP Chip Genotyping

Check the [relevant R script](MK130_SNP_genetic_diversity_script.R) for any
missing notes here on out!

Brassica 60k illumina infinium^TM SNP genotyping array

60k snps on this chip
- actually 52161 (presumably some nearest 2^n)
- actually nope! it's because some of the snps always fail and they round up 🙃

### IUPAC code for nucleotides
(Aside from ACTG):

- R g|a
- Y t|c pYramidin
- M a|c aMino
- K
- S
- W
- H
- B
- V
- D
- N aNy


SNP chip can be used for mapping, genotyping, LD (isn't that just mapping?)


file persample

winter types reduced genetic diversity since the harsher winter introduced
genetic bottlenecks

### Look at different measures of genetic diversity

- Jost's D per Locus (fairly new)
  - H_o observed heterozyg
  - H_s expected heterozyg, within subpop (avg)
  - H_t expected heterozyg, pop
  
  
### Selective sweep

- shows you there is more diversity at a locus in one subpopulation than others
- indicates is could be useful for adaptation
- then go and try to find the genes themselves (GWAS)
- first step towards getting into the evolutionary history of a species


select 3 for winter or spring oilseed rape program