---
title: "README"
author: "Alisa Röring / Sammi Johnson"
date: "2025-12-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Instructions

## Your Presentations
Your presentations should take 10 min, so 5 min per person, plus 10 min
questions from the audience (including me). The ability to answer questions
will be taken into account.
Each group will have a different set of plants, so your results will all be a bit
different.
**Your task is to select three accessions as donors for a future breeding
program on winter oilseed rape.** They should be genetically as diverse as
possible, but still be as adapted as possible.
In your presentation, you have to justify your selection.

## Your Data
You will have two data sets: phenotyping data from today as well as
genotypic data from next time (3./4. 12.25). Both can and should be used for
the presentation. There is no rule of how you distribute the work among
you, as long as both of you are presenting.
If you want more data, feel free to ask for it – the diversity set has been
heavily used in research in the last decades…

## Scoring
- Structure of the talk (2)
- Description of methods (2)
- Scientific quality of the figures, tables etc. (2)
- Arguments for selection (4)
- Presentation style (3)
- Ability to answer questions correctly (2)

## Which Traits Are Measured And Why?

### Seed Quality

> „Wild type rapeseed contained different antinutritive compounds, limiting use as
feed or food.
>
Discovery of the accession ‚Liho‘ in 1963 with
strongly reduced content in erucic acid lead to
the development of ‚0 rapeseed‘ – suitable for
human consumption.
>
Shortly afterwards, discovery of the accession
‚Bronowski‘ with reduced glucosinolate
content allowed development of ‚00 rapeseed‘
– suitable as animal feed and turning rapeseed
into a profitable crop”

**Takeaway:** seed quality corresponds with lower antinutrients like erucic acid 
and glucosinolate content.

### Seed Weight

> „Hundred grain weight is an important yield component”

**Takeaway:** Oilseed rape harvests the seed of course, so we want them as big and
(getting to this with yield later) as many of them per plant as possible.

### Plant Height And Biomass (Fresh And Dry)

> „Plant height and biomass are indicators of source capacity”

**Takeaway:** TBD

### Plant Development

> „Plant development needs to be perfectly synchronized”

Question for us to answer: What development do we want for this type of crop?
Is faster development actually worse?

**Takeaway:** TBD

### Chlorophyll Content

> „Chlorophyll content is a measure of N supply and stress level”

Question for us: What chlorophyll content is optimal for WOSR?

**Takeaway:** TBD

## Plant Material
> „I selected 12 diverse accessions of
Brassica napus (rapeseed) from a
larger diversity set (>500
accessions).
They were grown in the
greenhouse in pots in 5 replicates
under Standard conditions for 5
weeks. Details can be found in the
document
„MP258_plant_cultivation.pdf“.”

|    ASSYST_ID    |    Name                       |    TYPE       |
| :-------------- | :---------------------------- | :------------ |
| BnASSYST-078    | Express 617                   | Winter OSR    |
| BnASSYST-120    | Darmor                        | Winter OSR    |
| BnASSYST-145    | Hokkai 3-Go                   | Winter OSR    |
| BnASSYST-210    | RED RUSSIAN                   | Siberian kale |
| BnASSYST-211    | SIBERISCHE_BOERENKOOL         | Siberian kale |
| BnASSYST-219    | GRÜNER SCHNITTKOHL            | Siberian kale |
| BnASSYST-271    | Liho                          | Spring OSR    |
| BnASSYST-273    | Bronowski                     | Spring OSR    |
| BnASSYST-290    | Ability                       | Spring OSR    |
| BnASSYST-419    | Angus                         | swede         |
| BnASSYST-424    | Conqueror Bronze Green Top    | swede         |
| BnASSYST-427    | Essex Model                   | swede         |




# Notes

## TO-DO:
 
- Give weights to traits for multi-trait score (Which traits are more important than others)
- Find out if lower or higher plant height is best for winter rape seed
- Discuss what to do about the Flowering Times
- Write a script to calculate the multi-trait-score
- Decide what kind of PCAs we want to do
- ???


## Primary objectives:
- Evaluate multiple genotypes based on their traits
- Calculate Multi-Trait Score to assess overall performance for each genotype.
- Use PCA to visualize phenotypic or genetic variability among genotypes.
- Select three genotypes that combine:
- high performance/quality (Multi-Trait-Score) and
- High genetic diversity  (PCA)


## Multi-Trait Score
 
We wanna combine several meaningful traits into a single numerical value that reflects the overall performance of each genotype.
This score is based only on traits that show clear and significant! genetic variation.
 
### BLUP = Best Linear Unbiased Prediction
A statistical estimate of the genetic performance of a genotype. BLUPs represent the genetic value of a genotype for a trait!

Corrects for:
- environmental effects
- replicate/block effects
- random error
 
### EBLUP = Estimated BLUP
- This is simply: EBLUP = BLUP + grand mean
- BLUPs alone are centered around zero so they are sucky to read
- EBLUPs shift the predictions back to the original trait scale, making them comparable and interpretable.
- For PCA and multi-trait scoring, EBLUPs are typically used so we are doing that, too.
 

## Traits Included in the Multi-Trait Score
Only traits with a significant genotype effect (p < 0.05)
 
Included traits (BLUP/EBLUP used):
- SQI (Seed Quality Index) this I have calculated using the measured traits from the seed quality sheet they provided [Updated with Sarah's input!]
- CCM (Chlorophyll Content)
- HGW (Hundred Grain Weight)
- Fresh Mass (FM) 
  - "After sampling" was incomplete and I left it out because I didn't see the use of it.
- Dry Weight (DW)
- Plant Height (PH)
- BBCH

## Traits Excluded from the Multi-Trait Score
I excluded them because the genotype had no significant effect on the trait (Flowering Time) or because I was uncertain.
 
Flowering Type (FT): Genotype had no significant effect on flowering type


## NEW: KASP ANALYSIS

- AA -> RLM4
- CC -> RLM7 or RLM9
- AC -> Carries all 3 but we only have homozygotes I think?


## What I did so far:
 
- Extracted BLUPS and EBLUPS for the relevant traits [Update: Included Thursday Datsets]
- Calculated Means for FT 
- Put the data into an excel file for overview

## Questions (bad) :
 
- Which traits do we include in the PCAs?
- Do we include only EBLUPS in PCAs? Or can means be used from traits that have no effect on genotype? 
  - Maybe BBCH and FT for developmental PCA? DOES THAT EVEN MAKE SENSE?
- What kind of PCAs are we gonna do?
 
 
### BBCH:
- How do we handle this trait? Is it influenced strongly genetically or is it environmental?
- Is it a performance trait? Or a diversity trait? Phenological diversity vs perfomance quality?
- Is higher BBCH = Better? Or should it only be included in a developmental PCA?
- Is smaller plant height better?




## Questions (good):
(Qs I would like to answer with PCAs)
 
- Which of these traits explain most of the performance variation?
- Which genotypes perform similarly across all traits?
- Are high-scoring genotypes diverse or not? Are top-performers clustering tightly or spread out?
- Do some traits co-vary?
- Are there like.. How do you say in english? Trade-offs? Like High something but low something else?
